; Use this AutoHotkey script to determine your button mappings:
; https://www.autohotkey.com/docs_1.0/scripts/JoystickTest.htm

[XbarLeft]
POV_Up=0
POV_Down=18000
POV_Left=27000
POV_Right=9000

[XbarRight]
Button_Up=4
Button_Down=1
Button_Left=3
Button_Right=2

[FunctionMap]
Button_Confirm=1
Button_Cancel=2
Button_MainMenu=4
Button_ActiveWindow=3
Button_ToggleBind=7
Button_CycleSets=8
Button_XbarLeft=5
Button_XbarRight=6
